### ISSUE TITLE
Hide reCAPTCHA response from PR body

### ISSUE THREAD

**Issue by VincentTam** [TerminalAddict/loudas.com-website#23]
Hi, this is the maintainer of @staticmanlab.  For each static comment, the reCAPTCHA response is displayed in the PR body.  IMHO, it's not worth keeping track of that since that's not part of the site's static content.  It's possible to implement reCAPTCHA without recording the response in the repo.  You may take a look at some popular themes like Minimal Mistakes and Beautiful Hugo for reference.

**Comment by TerminalAddict** [comment]
cool, thanks for the tip, I'll do some research with my code :)
